# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "734046a660dafe32ac3fe23e6f18f46a88a0a65c"

[[deps.AverageLoglikelihoodRatio]]
deps = ["Random"]
path = "."
uuid = "06875939-83ae-4909-8529-2b6af0a65917"
version = "0.0.1"

[[deps.Random]]
deps = ["SHA"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
version = "1.11.0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"
